import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { Providers } from "./provider";
import { ThemeSwitcher } from "./components/ThemeSwitcher ";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DJ Jackpot",
  description: "Generated by Phuti Sekwadi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <ThemeSwitcher />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
