import { Metadata } from 'next';
import Link from 'next/link';
import React from 'react';

export const metadata: Metadata = {
    title: "DJ Jackpot Admin",
    description: "Generated by CodeTechX",
};

export default function Admin() {
    return (
        <div className='max-w-6xl p-3 mx-auto'>
            <h1 className='p-5 mb-3 font-bold text-center text-3xl text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-red-500'>DJ JACKPOT ADMIN PAGE</h1>
            <div className='grid grid-cols-1 md:grid-cols-3 gap-3'>
                <div className='flex flex-col items-center justify-between h-40 w-full p-4 border border-gray-800 rounded-xl shadow-lg'>
                    <h2>Add Mixtape</h2>
                    <Link href={'/mamabolo/add'} className='w-full rounded-md text-center px-5 py-2 bg-blue-400 hover:bg-blue-600 text-white font-bold'>
                        Add Mixtape
                    </Link>
                </div>
                <div className='flex flex-col items-center justify-between h-40 w-full p-4 border border-gray-800 rounded-xl shadow-lg'>
                    <h2>Add event</h2>
                    <Link href={'/mamabolo/event'} className='w-full rounded-md text-center px-5 py-2 bg-blue-400 hover:bg-blue-600 text-white font-bold'>
                        Add Event
                    </Link>
                </div>
                <div className='flex flex-col items-center justify-between h-40 w-full p-4 border border-gray-800 rounded-xl shadow-lg'>
                    <h2>Profile</h2>
                    <Link href={'/mamabolo/profile'} className='w-full rounded-md text-center px-5 py-2 bg-blue-400 hover:bg-blue-600 text-white font-bold'>
                        Profile
                    </Link>
                </div>
            </div>
        </div>
    );
}

